/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardLedgerRouteImport } from './routes/dashboard.ledger'
import { Route as DashboardIssueRouteImport } from './routes/dashboard.issue'
import { Route as CredentialIdRouteImport } from './routes/credential.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerRoute = DashboardLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssueRoute = DashboardIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => DashboardRoute,
} as any)
const CredentialIdRoute = CredentialIdRouteImport.update({
  id: '/credential/$id',
  path: '/credential/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/credential/$id': typeof CredentialIdRoute
  '/dashboard/issue': typeof DashboardIssueRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/credential/$id': typeof CredentialIdRoute
  '/dashboard/issue': typeof DashboardIssueRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/credential/$id': typeof CredentialIdRoute
  '/dashboard/issue': typeof DashboardIssueRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/register'
    | '/verify'
    | '/credential/$id'
    | '/dashboard/issue'
    | '/dashboard/ledger'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/verify'
    | '/credential/$id'
    | '/dashboard/issue'
    | '/dashboard/ledger'
    | '/dashboard/templates'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/register'
    | '/verify'
    | '/credential/$id'
    | '/dashboard/issue'
    | '/dashboard/ledger'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  CredentialIdRoute: typeof CredentialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger': {
      id: '/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issue': {
      id: '/dashboard/issue'
      path: '/issue'
      fullPath: '/dashboard/issue'
      preLoaderRoute: typeof DashboardIssueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/credential/$id': {
      id: '/credential/$id'
      path: '/credential/$id'
      fullPath: '/credential/$id'
      preLoaderRoute: typeof CredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIssueRoute: typeof DashboardIssueRoute
  DashboardLedgerRoute: typeof DashboardLedgerRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIssueRoute: DashboardIssueRoute,
  DashboardLedgerRoute: DashboardLedgerRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  CredentialIdRoute: CredentialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
